# Generated by Django 4.1.7 on 2023-06-12 16:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bodyinforecord',
            name='user_body_info',
        ),
        migrations.AddField(
            model_name='bodyinforecord',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='body_info_record', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userbodyinfo',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_body_info', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
