# Generated by Django 4.1.7 on 2023-06-12 16:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_bodyinforecord_user_body_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bodyinforecord',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='body_info_record', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userbodyinfo',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_body_info', to=settings.AUTH_USER_MODEL),
        ),
    ]
