# Generated by Django 4.1.7 on 2023-04-13 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('meals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diet_kcal', models.IntegerField(default=0)),
                ('diet_protein', models.IntegerField(default=0)),
                ('diet_fat', models.IntegerField(default=0)),
                ('diet_carbs', models.IntegerField(default=0)),
                ('meals', models.ManyToManyField(related_name='days', to='meals.meal')),
            ],
        ),
        migrations.CreateModel(
            name='WeekDiet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_kcal', models.IntegerField(default=0)),
                ('week_protein', models.IntegerField(default=0)),
                ('week_fat', models.IntegerField(default=0)),
                ('week_carbs', models.IntegerField(default=0)),
                ('bodyinfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weeks', to='accounts.bodyinforecord')),
                ('diets', models.ManyToManyField(related_name='weeks', to='diets.diet')),
            ],
        ),
    ]
