# Generated by Django 4.1.7 on 2023-04-09 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '__first__'),
        ('meals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DietOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('options', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WeekDiet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('BodyInfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weeks', to='accounts.bodyinforecord')),
                ('diet_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weeks', to='diets.dietoption')),
            ],
        ),
        migrations.CreateModel(
            name='Diet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(max_length=50)),
                ('diet_kcal', models.IntegerField(default=0)),
                ('diet_protein', models.IntegerField(default=0)),
                ('diet_fat', models.IntegerField(default=0)),
                ('diet_carbs', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('diet_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='diets.dietoption')),
                ('meals', models.ManyToManyField(related_name='days', to='meals.meal')),
                ('week_diet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='diets.weekdiet')),
            ],
        ),
    ]
