# Generated by Django 4.1.7 on 2023-05-16 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diet',
            name='category',
        ),
        migrations.RemoveField(
            model_name='weekdiet',
            name='categories',
        ),
    ]
