# Generated by Django 4.1.7 on 2023-04-13 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('diets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weekdiet',
            name='bodyinfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weeks', to='accounts.userbodyinfo'),
        ),
    ]
