# Generated by Django 4.1.7 on 2023-05-05 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diet',
            name='meals_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='weekdiet',
            name='meals_count',
            field=models.IntegerField(default=0),
        ),
    ]
