# Generated by Django 4.1.7 on 2023-04-13 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diets', '0002_alter_weekdiet_bodyinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='weekdiet',
            name='diet_status',
            field=models.IntegerField(default=0),
        ),
    ]
