# Generated by Django 4.1.7 on 2023-05-05 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diets', '0002_diet_meals_count_weekdiet_meals_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diet',
            old_name='meals_count',
            new_name='meal_count',
        ),
        migrations.RenameField(
            model_name='weekdiet',
            old_name='meals_count',
            new_name='meal_count',
        ),
    ]
