# Generated by Django 4.1.7 on 2023-05-17 02:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0001_initial'),
        ('diets', '0002_remove_diet_category_remove_weekdiet_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='diet',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='foods.foodcategory'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weekdiet',
            name='categories',
            field=models.ManyToManyField(to='foods.foodcategory'),
        ),
    ]
