# Generated by Django 4.1.7 on 2023-04-13 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diets', '0003_weekdiet_diet_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weekdiet',
            name='diet_status',
        ),
    ]
