# Generated by Django 4.1.7 on 2023-03-28 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('meal', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DietOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('options', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WeekDiet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('BodyInfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weeks', to='accounts.bodyinforecord')),
                ('diet_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weeks', to='diet.dietoption')),
            ],
        ),
        migrations.CreateModel(
            name='Diet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(max_length=50)),
                ('total_kcal', models.IntegerField()),
                ('tital_protein', models.IntegerField()),
                ('total_fat', models.IntegerField()),
                ('total_carbs', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('diet_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='diet.dietoption')),
                ('meals', models.ManyToManyField(related_name='days', to='meal.meal')),
                ('week_diet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='diet.weekdiet')),
            ],
        ),
    ]
