version: '3'

services:
  nginx:
    container_name: nginx
    build:
      context: ./web
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "80:80"
      - "8000:8000"
    depends_on:
      - django_app
      - react_app
      
  django_app:
    build:
      context: backend
      dockerfile: Dockerfile
    command: bash -c "cd backend && gunicorn --bind 0.0.0.0:8000 Simple_Diet_Manager.wsgi:application"
    expose:
      - "8000"
    volumes:
      - .:/app

      
  react_app:
    build:
      context: frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
    expose:
      - "3000"