# Generated by Django 4.1.7 on 2023-04-13 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='iscoupangfresh',
        ),
    ]
