# Generated by Django 4.1.7 on 2023-04-06 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodcategory',
            name='img',
            field=models.ImageField(default=1, upload_to='backend/foodcategory_img'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='food',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='backend/food_img'),
        ),
    ]
