# Generated by Django 4.1.7 on 2023-04-07 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0002_foodcategory_img_alter_food_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='food-img/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='foodcategory',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='food-category/%Y/%m/%d/'),
        ),
    ]
