# Generated by Django 4.1.7 on 2023-05-05 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='meal_count',
            field=models.IntegerField(default=3),
        ),
    ]
