# Generated by Django 4.1.7 on 2023-04-06 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='meal_img',
            field=models.ImageField(blank=True, null=True, upload_to='backend/meal_img'),
        ),
    ]
