# Generated by Django 4.1.7 on 2023-04-07 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0002_meal_meal_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='meal_img',
            field=models.ImageField(blank=True, null=True, upload_to='meal/%Y/%m/%d/'),
        ),
    ]
