# Generated by Django 4.1.7 on 2023-03-29 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_rename_cooking_food_cookingoptions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='cookingoptions',
            new_name='cookingoption',
        ),
    ]
