# Generated by Django 4.1.7 on 2023-03-29 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_rename_cookingoptions_food_cookingoption'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='isfresh',
            field=models.BooleanField(default=False),
        ),
    ]
