# Generated by Django 4.1.7 on 2023-03-29 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_food_isfresh'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='isfresh',
            new_name='iscoupangfresh',
        ),
    ]
