# Generated by Django 4.1.7 on 2023-03-29 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meal',
            old_name='tital_protein',
            new_name='meal_carbs',
        ),
        migrations.RenameField(
            model_name='meal',
            old_name='total_carbs',
            new_name='meal_fat',
        ),
        migrations.RenameField(
            model_name='meal',
            old_name='total_fat',
            new_name='meal_kcal',
        ),
        migrations.RenameField(
            model_name='meal',
            old_name='total_kcal',
            new_name='meal_protein',
        ),
    ]
