# Generated by Django 4.1.7 on 2023-03-29 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0002_rename_tital_protein_meal_meal_carbs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='meal_carbs',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='meal',
            name='meal_fat',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='meal',
            name='meal_kcal',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='meal',
            name='meal_protein',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='meal',
            name='meal_video',
            field=models.URLField(max_length=100, null=True),
        ),
    ]
