# Generated by Django 4.1.7 on 2023-03-29 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0003_alter_meal_meal_carbs_alter_meal_meal_fat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='meal_video',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
    ]
